# ===== Application =====
spring.application.name=factchecker

# ===== DataSource =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== OPEN_API_KEY =====
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini

# ===== Security Oauth =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/factchecker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/factchecker/protocol/openid-connect/certs
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

#==== keycloak ====
keycloak.auth-server-url=${KEYCLOAK_SERVER_URL:http://localhost:8081}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:factchecker-client}
keycloak.admin.username=${KEYCLOAK_ADMIN_ID:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.realm=factchecker

#==kakao login==#

spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}


spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-name=Kakao

#==== Kakao Provider Configuration===
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kapi.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute-name=id



# ===================================================================
# NAVER SMTP Mail Properties
# ===================================================================
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${NAVER_ID}
spring.mail.password=${NAVER_PASSWORD}

# SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.trust=smtp.naver.com

spring.mail.properties.mail.smtp.from=${NAVER_ID}



ai.openai.model.claim-analysis=${AI_CLAIM_ANALYSIS_MODEL:gpt-5.4-mini}
ai.openai.model.stance-analysis=${AI_STANCE_ANALYSIS_MODEL:gpt-5.4-mini}
ai.openai.model.fact-extraction=${AI_FACT_EXTRACTION_MODEL:gpt-5.4-mini}
ai.openai.model.embedding=${AI_EMBEDDING_MODEL:text-embedding-3-small}

# ==== OPEN_API_CONNECTION_TIME ====
spring.http.client.connect-timeout=5s
spring.http.client.read-timeout=60s


# ==== MOFA ====
mofa.api.base-url=https://apis.data.go.kr/1262000
mofa.api.service-key=${MOFA_SERVICE_KEY}
mofa.api.num-of-rows=20

