# ===== Application =====
spring.application.name=factchecker

# ===== DataSource =====
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== OPEN_API_KEY =====
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-mini
ai.openai.model.claim-analysis=${AI_CLAIM_ANALYSIS_MODEL:gpt-5.4-mini}
ai.openai.model.stance-analysis=${AI_STANCE_ANALYSIS_MODEL:gpt-5.4-mini}
ai.openai.model.embedding=${AI_EMBEDDING_MODEL:text-embedding-3-small}

# ===== Security Oauth =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/factchecker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/factchecker/protocol/openid-connect/certs

# ==== MOFA ====
mofa.api.base-url=https://apis.data.go.kr/1262000
mofa.api.service-key=${MOFA_SERVICE_KEY}
mofa.api.num-of-rows=20
